// Generated by https://quicktype.io

export interface Domicilio {
  id:         number;
  estado:     string;
  municipio:  string;
  cp:         number;
  colonia:    string;
  referencia: string;
}
