// Generated by https://quicktype.io

export interface ProducsToCard {
  id:              number;
  nombre_producto: string;
  precio:          number;
  cantidad:        number;
  img:             string;
  usuarioId:       number;
}
