// Generated by https://quicktype.io

export interface Products {
  id:              number;
  nombre_producto: string;
  precio:          number;
  descripccion:    string;
  stock:           number;
  categoria?:       Categoria;
  imagen:          string;
  rating:          number;
  descuento:       number;
}

export enum Categoria {
  Caballero = "Caballero",
  Dama = "Dama",
}
