name: CI - Angular Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'  # Asegúrate de usar la versión adecuada de Node.js

    - name: Install dependencies
      run: npm install

    - name: Run Jest tests
      run: npm test
