name: WebApp CI/CD Cypress # Nombre del flujo de trabajo

# Configuración de los desencadenadores
on:
  push:
    branches:
      - prueba3             # Ejecutar en cada push a las ramas especificadas
      - luis-jair
      - mabel       
  pull_request:
    branches:
      - main
    
  workflow_dispatch:

# Permisos para GitHub Actions
permissions:
  contents: read

jobs:
  CypressTests:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Versión de Node.js recomendada
          cache: 'npm'  # Configura el caché para npm automáticamente

      # 3. Instalar dependencias del proyecto
      - name: Install dependencies
        run: npm install

      # 4. Levantar la aplicación de Angular en localhost con `ng serve`
      - name: Start Angular App
        run: ng serve --host 0.0.0.0 --disable-host-check --port 4200 &
        env:
          CI: true

      # 5. Esperar a que el servidor esté disponible
      - name: Wait for Angular App to be available
        run: npx wait-on http://localhost:4200

      # 6. Ejecutar pruebas E2E con Cypress
      - name: Run Cypress tests
        run: npx cypress run

      # 7. Ejecutar pruebas de lint (opcional, recomendado)
      - name: Run lint test
        run: npm run lint
