name: Angular CI with Jest

on:
  push:
    branches:
      - mabel
  pull_request:
    branches:
      - mabel

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]  # Puedes especificar las versiones de Node.js que quieres usar

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Run tests with Jest
      run: npm run test -- --ci --runInBand --detectOpenHandles
